### ISSUE TITLE
crispy_forms

### ISSUE THREAD

**Issue by saqibaloch** [EngDiesel/pyShop#1]
Got following message while try to start server
ModuleNotFoundError: No module named 'crispy_forms'

**Comment by EngDiesel** [comment]
@saqilbaloch can you please provide more information about the file and line number?

**Comment by EngDiesel** [comment]
> Got following message while try to start server
> ModuleNotFoundError: No module named 'crispy_forms'

Make Sure to install all the requirements before you run the server.
You can easily run the file `build-project.sh` or if you want to install them manually open up your **bash terminal**, make sure you are in the `src/` directory and run the following comman `pip install -r requirements.txt`.

**Comment by EngDiesel** [comment]
> Got following message while try to start server
> ModuleNotFoundError: No module named 'crispy_forms'

**@saqilbaloch** can you please provide more information about the _file and line number_?
